// Even Fibonacci Numbers

// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

function evenFib() {
	let result = 0; // keeps track of even-valued terms sum
	let x = 1; // first fibonacci #
	let y = 2; // second fibonacci #

	while (x <= 4000000) {
		if (x % 2 === 0) {
			result += x; // add the current term to result if it is even
		}

		[x, y] = [y, x + y]; // first # becomes the second #, and second # becomes sum of x + y
	}

	return result;
}

console.log(evenFib());

// Answer:
// 4613732
